### ISSUE TITLE
datetime to variable now issue

### ISSUE THREAD

**Issue by eirik-L** [Reftab/ReftabPython#1]
now = datetime.now().strftime('%Y-%m-%dT%H:%M:%S%z')
this gives out the value, in format: 2021-10-08T08:28:20
and gives out an error: {'error': 'expired request'}

But if using, for example:
import email.utils
now = email.utils.formatdate(usegmt=True)
you get the value: Fri, 08 Oct 2021 05:28:20 GMT
and this seems to be working correctly :)

**Comment by rvhoyt** [comment]
Thanks for this. Changed to suggested format and tested. Seems to work.
