### ISSUE TITLE
Error when getting an asset

### ISSUE THREAD

**Issue by ankorjega** [Reftab/ReftabPython#3]
Hello @rvhoyt ,

Thanks for the python module but unfortunately I have a problem when I execute it. 
I have a main where I have copied and pasted your example to get an asset and update it, I have the error below 
`Traceback (most recent call last):
  File "/home/jega/./main.py", line 11, in <module>
    asset = client.get('assets', 'OSX-FVHG32Z')
  File "/home/jega/reftab/Client.py", line 61, in get
    return self.__request('GET', endpoint)
  File "/home/jega/reftab/Client.py", line 34, in __request
    key=self.secretKey.encode('utf-8'),
AttributeError: 'list' object has no attribute 'encode'`

Do you know from where it can be?

Thanks.

**Comment by rvhoyt** [comment]
I believe you're putting your keys in as lists instead of just strings.

secretKey=[secretKey],
publicKey=[publicKey]

Should be populated as
secretKey="key1",
publicKey="key2"

Not as 
secretKey=["key1"],
publicKey=["key2"]

**Comment by ankorjega** [comment]
You were right @rvhoyt .
But now I have this error:
`HTTP Error 404: Not Found
{'error': 'no assets found'}
Traceback (most recent call last):
  File "/home/jega/./main.py", line 13, in <module>
    asset['title'] = 'New Title'
TypeError: 'NoneType' object does not support item assignment`

in the client.get, do I need to put the asset name or id ?
Thanks.

**Comment by ankorjega** [comment]
I got my answer, it's ID, thanks for your help. You can close this.

**Comment by rvhoyt** [comment]
You need to put the asset id when doing client.get('assets', 'asset#')
Your request returned a 404, not found error, so the asset id you tried to search for was not found.
It is the equivalent of calling this endpoint: https://www.reftab.com/api-docs/#get-/assets/{aid}
