### ISSUE TITLE
increase default request limit

### ISSUE THREAD

**Issue by XeroxBrain** [Reftab/ReftabPython#4]
Hello @rvhoyt ,

Thanks for the work on the module.
Is it possible to increase the default request limit in your client.py ?
By default 100, so with one request we might not get all assets.
Thanks.

**Comment by rvhoyt** [comment]
The default is set by the API server not the client. You can override it by setting a parameter in your request.
Example:
assets = client.get('assets?limit=500')
Other parameters can be found here for that endpoint:
https://www.reftab.com/api-docs/#get-/assets
